export const collectionVariables = {
  "konnect_base_url": "https://in.api.konghq.com",
  "konnect_pat": "",
  "control_plane_id": "78ac8c8b-74a8-4338-875f-2ccaee19a52c",
  "proxy_url": "https://b72e60ba26.us.serverless.gateways.konggateway.com",
  "service_id": "",
  "service_name": "",
  "route_id": "",
  "route_name": "",
  "consumer_id": "",
  "consumer_username": "",
  "plugin_id": "",
  "upstream_id": "",
  "upstream_name": "",
  "target_id": "",
  "certificate_id": "",
  "sni_id": "",
  "ca_certificate_id": "",
  "vault_id": "",
  "jwt_credential_id": "",
  "keyauth_credential_id": "",
  "basicauth_credential_id": "",
  "hmacauth_credential_id": "",
  "oauth2_credential_id": "",
  "acl_id": "",
  "jwt_token": ""
} as const;
